export const servicesMockData = [
  {
    id: "SVC-1001",
    nome: "Troca de Óleo",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 120,00",
  },
  {
    id: "SVC-1002",
    nome: "Alinhamento",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 80,00",
  },
  {
    id: "SVC-1003",
    nome: "Balanceamento",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 60,00",
  },
  {
    id: "SVC-1004",
    nome: "Troca de Pastilhas de Freio",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 250,00",
  },
  {
    id: "SVC-1005",
    nome: "Higienização do Ar Condicionado",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 150,00",
  },
  {
    id: "SVC-1006",
    nome: "Revisão Completa",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 480,00",
  },
  {
    id: "SVC-1007",
    nome: "Diagnóstico Eletrônico",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 90,00",
  },
  {
    id: "SVC-1008",
    nome: "Troca de Velas",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 180,00",
  },
  {
    id: "SVC-1009",
    nome: "Limpeza de Bicos Injetores",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 220,00",
  },
  {
    id: "SVC-1010",
    nome: "Suspensão Dianteira",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 350,00",
  },
  {
    id: "SVC-1011",
    nome: "Troca de Filtro de Ar",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 70,00",
  },
  {
    id: "SVC-1012",
    nome: "Troca de Filtro de Combustível",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 75,00",
  },
  {
    id: "SVC-1013",
    nome: "Reparo no Sistema de Freios",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 420,00",
  },
  {
    id: "SVC-1014",
    nome: "Limpeza do Sistema de Arrefecimento",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 300,00",
  },
  {
    id: "SVC-1015",
    nome: "Scanner Automotivo",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 100,00",
  },
  {
    id: "SVC-1016",
    nome: "Troca de Embreagem",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 1.200,00",
  },
  {
    id: "SVC-1017",
    nome: "Troca de Correia Dentada",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 650,00",
  },
  {
    id: "SVC-1018",
    nome: "Geometria 3D",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 140,00",
  },
  {
    id: "SVC-1019",
    nome: "Polimento Técnico",
    tipoCobranca: { label: "REAL", variant: "success" },
    valor: "R$ 280,00",
  },
  {
    id: "SVC-1020",
    nome: "Lavagem Completa",
    tipoCobranca: { label: "Un. de Serviço", variant: "info" },
    valor: "R$ 50,00",
  },
];