export const servicesMockData = [
  {
    id: "SVC-1001",
    nome: "Troca de Óleo",
    tipoCobranca: "REAL",
    valor: "R$ 120,00",
  },
  {
    id: "SVC-1002",
    nome: "Alinhamento",
    tipoCobranca: "UNIDADE",
    valor: "R$ 80,00",
  },
  {
    id: "SVC-1003",
    nome: "Balanceamento",
    tipoCobranca: "UNIDADE",
    valor: "R$ 60,00",
  },
  {
    id: "SVC-1004",
    nome: "Troca de Pastilhas de Freio",
    tipoCobranca: "REAL",
    valor: "R$ 250,00",
  },
  {
    id: "SVC-1005",
    nome: "Higienização do Ar Condicionado",
    tipoCobranca: "REAL",
    valor: "R$ 150,00",
  },
  {
    id: "SVC-1006",
    nome: "Revisão Geral",
    tipoCobranca: "REAL",
    valor: "R$ 300,00",
  },
  {
    id: "SVC-1007",
    nome: "Diagnóstico Eletrônico",
    tipoCobranca: "REAL",
    valor: "R$ 180,00",
  },
  {
    id: "SVC-1008",
    nome: "Troca de Velas",
    tipoCobranca: "UNIDADE",
    valor: "R$ 90,00",
  },
  {
    id: "SVC-1009",
    nome: "Limpeza de Bicos Injetores",
    tipoCobranca: "REAL",
    valor: "R$ 220,00",
  },
  {
    id: "SVC-1010",
    nome: "Troca de Correia Dentada",
    tipoCobranca: "REAL",
    valor: "R$ 450,00",
  },
  {
    id: "SVC-1011",
    nome: "Alinhamento + Balanceamento",
    tipoCobranca: "UNIDADE",
    valor: "R$ 130,00",
  },
  {
    id: "SVC-1012",
    nome: "Troca de Filtro de Ar",
    tipoCobranca: "UNIDADE",
    valor: "R$ 50,00",
  },
  {
    id: "SVC-1013",
    nome: "Troca de Filtro de Óleo",
    tipoCobranca: "UNIDADE",
    valor: "R$ 45,00",
  },
  {
    id: "SVC-1014",
    nome: "Suspensão Dianteira",
    tipoCobranca: "REAL",
    valor: "R$ 380,00",
  },
  {
    id: "SVC-1015",
    nome: "Balanceamento Dinâmico",
    tipoCobranca: "UNIDADE",
    valor: "R$ 70,00",
  },
  {
    id: "SVC-1016",
    nome: "Scanner Automotivo Completo",
    tipoCobranca: "REAL",
    valor: "R$ 200,00",
  },
  {
    id: "SVC-1017",
    nome: "Troca de Embreagem",
    tipoCobranca: "REAL",
    valor: "R$ 900,00",
  },
  {
    id: "SVC-1018",
    nome: "Reparo no Sistema de Freios",
    tipoCobranca: "REAL",
    valor: "R$ 320,00",
  },
  {
    id: "SVC-1019",
    nome: "Limpeza do Sistema de Arrefecimento",
    tipoCobranca: "REAL",
    valor: "R$ 210,00",
  },
  {
    id: "SVC-1020",
    nome: "Troca de Amortecedores",
    tipoCobranca: "REAL",
    valor: "R$ 600,00",
  },
];