import {
    FaCheckCircle,
    FaClock,
    FaPlayCircle,
    FaRegDotCircle,
} from "react-icons/fa";

export const pedidosMockData = [
    {
        id: "OS-1024",
        numero: "1024",
        cliente: "Marcelo Alves",
        categoria: "Refrigeração",
        dataAbertura: "2026-05-20",
        status: { label: "Finalizado", variant: "success", icon: FaCheckCircle },
        prioridade: { label: "Alta", variant: "danger", icon: FaRegDotCircle },
        responsavel: "Lina Souza",
        valor: "R$ 1.280,00",
    },
    {
        id: "OS-1025",
        numero: "1025",
        cliente: "Oficina Central",
        categoria: "Elétrica",
        dataAbertura: "2026-05-21",
        status: { label: "Em execução", variant: "warning", icon: FaPlayCircle },
        prioridade: { label: "Média", variant: "info", icon: FaClock },
        responsavel: "Carlos Lima",
        valor: "R$ 860,00",
    },
    {
        id: "OS-1026",
        numero: "1026",
        cliente: "Rede Norte",
        categoria: "Hidráulica",
        dataAbertura: "2026-05-21",
        status: { label: "Aberto", variant: "info", icon: FaClock },
        prioridade: { label: "Baixa", variant: "neutral", icon: FaRegDotCircle },
        responsavel: "Fernanda Rocha",
        valor: "R$ 540,00",
    },
    {
        id: "OS-1027",
        numero: "1027",
        cliente: "Atende Mais",
        categoria: "Manutenção Geral",
        dataAbertura: "2026-05-22",
        status: { label: "Aberto", variant: "info", icon: FaClock },
        prioridade: { label: "Alta", variant: "danger", icon: FaRegDotCircle },
        responsavel: "Paulo Henrique",
        valor: "R$ 2.400,00",
    },
    {
        id: "OS-1028",
        numero: "1028",
        cliente: "Mercado Bom Preço",
        categoria: "Refrigeração",
        dataAbertura: "2026-05-22",
        status: { label: "Finalizado", variant: "success", icon: FaCheckCircle },
        prioridade: { label: "Média", variant: "info", icon: FaClock },
        responsavel: "Lina Souza",
        valor: "R$ 980,00",
    },
    {
        id: "OS-1029",
        numero: "1029",
        cliente: "Residencial Souza",
        categoria: "Elétrica",
        dataAbertura: "2026-05-22",
        status: { label: "Aberto", variant: "info", icon: FaClock },
        prioridade: { label: "Baixa", variant: "neutral", icon: FaRegDotCircle },
        responsavel: "Carlos Lima",
        valor: "R$ 420,00",
    },
    {
        id: "OS-1030",
        numero: "1030",
        cliente: "Polo Industrial",
        categoria: "Automação",
        dataAbertura: "2026-05-23",
        status: { label: "Em execução", variant: "warning", icon: FaPlayCircle },
        prioridade: { label: "Alta", variant: "danger", icon: FaRegDotCircle },
        responsavel: "Fernanda Rocha",
        valor: "R$ 3.150,00",
    },
    {
        id: "OS-1031",
        numero: "1031",
        cliente: "Padaria Nova Era",
        categoria: "Hidráulica",
        dataAbertura: "2026-05-23",
        status: { label: "Aberto", variant: "info", icon: FaClock },
        prioridade: { label: "Média", variant: "info", icon: FaClock },
        responsavel: "Paulo Henrique",
        valor: "R$ 730,00",
    },
    {
        id: "OS-1032",
        numero: "1032",
        cliente: "Clínica Vital",
        categoria: "Climatização",
        dataAbertura: "2026-05-24",
        status: { label: "Finalizado", variant: "success", icon: FaCheckCircle },
        prioridade: { label: "Baixa", variant: "neutral", icon: FaRegDotCircle },
        responsavel: "Lina Souza",
        valor: "R$ 1.020,00",
    },
    {
        id: "OS-1033",
        numero: "1033",
        cliente: "Mercadinho Serra",
        categoria: "Elétrica",
        dataAbertura: "2026-05-24",
        status: { label: "Em execução", variant: "warning", icon: FaPlayCircle },
        prioridade: { label: "Alta", variant: "danger", icon: FaRegDotCircle },
        responsavel: "Carlos Lima",
        valor: "R$ 1.430,00",
    },
];