export const receivablesMockData = [
  { id: 1, date: "2026-05-01", description: "#OS-8821", client: "Ana Costa & Associados", category: "Ordem de Serviço", value: 180.0, paymentType: "À vista", paymentMethod: "Cartão de Crédito", paid: true },
  { id: 2, date: "2026-05-03", description: "#OS-8822", client: "Empresa XYZ", category: "Mensalidade", value: 250.0, paymentType: "Recorrente", paymentMethod: "Boleto", paid: false },
  { id: 3, date: "2026-05-05", description: "Venda de Licença", client: "Tech Solutions", category: "Vendas", value: 1500.0, paymentType: "À vista", paymentMethod: "Transferência", paid: true },
  { id: 4, date: "2026-05-10", description: "Consultoria Maio", client: "Grupo Alfa", category: "Consultoria", value: 3200.0, paymentType: "Parcelado", paymentMethod: "Boleto", paid: true },
  { id: 5, date: "2026-05-12", description: "#OS-8825", client: "Marcos Silva", category: "Ordem de Serviço", value: 90.0, paymentType: "À vista", paymentMethod: "Pix", paid: true },
  { id: 6, date: "2026-05-15", description: "Manutenção Preventiva", client: "Condomínio Flores", category: "Contrato", value: 850.0, paymentType: "Recorrente", paymentMethod: "Boleto", paid: false },
  { id: 7, date: "2026-05-18", description: "Venda de Equipamento", client: "Clínica Saúde", category: "Vendas", value: 4500.0, paymentType: "Parcelado", paymentMethod: "Cartão de Crédito", paid: true },
  { id: 8, date: "2026-05-20", description: "Treinamento Equipe", client: "Agência Criativa", category: "Treinamento", value: 1200.0, paymentType: "À vista", paymentMethod: "Transferência", paid: true },
  { id: 9, date: "2026-05-22", description: "#OS-8830", client: "João Pedro", category: "Ordem de Serviço", value: 150.0, paymentType: "À vista", paymentMethod: "Cartão de Débito", paid: false },
  { id: 10, date: "2026-05-25", description: "Mensalidade Sistema", client: "Padaria Pão Quente", category: "Mensalidade", value: 199.9, paymentType: "Recorrente", paymentMethod: "Cartão de Crédito", paid: true },
  
  { id: 11, date: "2026-06-02", description: "#OS-8840", client: "Supermercado Boa Compra", category: "Ordem de Serviço", value: 340.0, paymentType: "À vista", paymentMethod: "Pix", paid: true },
  { id: 12, date: "2026-06-05", description: "Consultoria Junho", client: "Grupo Alfa", category: "Consultoria", value: 3200.0, paymentType: "Parcelado", paymentMethod: "Boleto", paid: false },
  { id: 13, date: "2026-06-08", description: "Atualização de Software", client: "Tech Solutions", category: "Serviço Avulso", value: 600.0, paymentType: "À vista", paymentMethod: "Transferência", paid: true },
  { id: 14, date: "2026-06-11", description: "#OS-8845", client: "Maria Oliveira", category: "Ordem de Serviço", value: 120.0, paymentType: "À vista", paymentMethod: "Dinheiro", paid: true },
  { id: 15, date: "2026-06-15", description: "Manutenção Preventiva", client: "Condomínio Flores", category: "Contrato", value: 850.0, paymentType: "Recorrente", paymentMethod: "Boleto", paid: true },
  { id: 16, date: "2026-06-18", description: "Venda de Licença Adicional", client: "Agência Criativa", category: "Vendas", value: 450.0, paymentType: "À vista", paymentMethod: "Cartão de Crédito", paid: false },
  { id: 17, date: "2026-06-21", description: "#OS-8850", client: "Restaurante Saboroso", category: "Ordem de Serviço", value: 210.0, paymentType: "À vista", paymentMethod: "Pix", paid: true },
  { id: 18, date: "2026-06-25", description: "Mensalidade Sistema", client: "Padaria Pão Quente", category: "Mensalidade", value: 199.9, paymentType: "Recorrente", paymentMethod: "Cartão de Crédito", paid: true },
  { id: 19, date: "2026-06-28", description: "Auditoria de Segurança", client: "Banco Nacional", category: "Consultoria", value: 8500.0, paymentType: "Parcelado", paymentMethod: "Transferência", paid: false },
  { id: 20, date: "2026-06-30", description: "#OS-8855", client: "Carlos Mendes", category: "Ordem de Serviço", value: 80.0, paymentType: "À vista", paymentMethod: "Cartão de Débito", paid: true },

  { id: 21, date: "2026-07-03", description: "Licença Anual", client: "Escola Aprender", category: "Vendas", value: 2400.0, paymentType: "À vista", paymentMethod: "Boleto", paid: true },
  { id: 22, date: "2026-07-06", description: "#OS-8860", client: "Livraria Leitura", category: "Ordem de Serviço", value: 160.0, paymentType: "À vista", paymentMethod: "Pix", paid: true },
  { id: 23, date: "2026-07-09", description: "Consultoria Julho", client: "Grupo Alfa", category: "Consultoria", value: 3200.0, paymentType: "Parcelado", paymentMethod: "Boleto", paid: false },
  { id: 24, date: "2026-07-12", description: "Instalação de Rede", client: "Startup Inovação", category: "Projeto", value: 5400.0, paymentType: "Parcelado", paymentMethod: "Transferência", paid: true },
  { id: 25, date: "2026-07-15", description: "Manutenção Preventiva", client: "Condomínio Flores", category: "Contrato", value: 850.0, paymentType: "Recorrente", paymentMethod: "Boleto", paid: true },
  { id: 26, date: "2026-07-18", description: "#OS-8865", client: "Fernanda Costa", category: "Ordem de Serviço", value: 110.0, paymentType: "À vista", paymentMethod: "Cartão de Crédito", paid: false },
  { id: 27, date: "2026-07-22", description: "Treinamento Avançado", client: "Tech Solutions", category: "Treinamento", value: 1800.0, paymentType: "À vista", paymentMethod: "Pix", paid: true },
  { id: 28, date: "2026-07-25", description: "Mensalidade Sistema", client: "Padaria Pão Quente", category: "Mensalidade", value: 199.9, paymentType: "Recorrente", paymentMethod: "Cartão de Crédito", paid: true },
  { id: 29, date: "2026-07-28", description: "Customização de App", client: "Agência Criativa", category: "Projeto", value: 2900.0, paymentType: "Parcelado", paymentMethod: "Transferência", paid: false },
  { id: 30, date: "2026-07-31", description: "#OS-8870", client: "Roberto Almeida", category: "Ordem de Serviço", value: 135.0, paymentType: "À vista", paymentMethod: "Dinheiro", paid: true }
];
